export const APP_NAME = "Palmtell";
export const APP_DESCRIPTION =
  "AI-powered palm reading — discover your personality, life path, and career insights from your palm.";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

export const DISCLAIMER =
  "Palmtell readings are generated by AI for entertainment purposes only. Not medical, psychological, financial, or legal advice.";

export const PLANS = {
  pro: {
    name: "Pro",
    monthlyPrice: 9.99,
    annualPrice: 95.90,
    readings: 10,
    profiles: 3,
    features: [
      "10 readings per month",
      "Up to 3 profiles",
      "All reading sections unlocked",
      "Daily & monthly horoscope",
      "Compatibility readings",
      "PDF export",
    ],
  },
  ultimate: {
    name: "Ultimate",
    monthlyPrice: 19.99,
    annualPrice: 191.90,
    readings: Infinity,
    profiles: Infinity,
    features: [
      "Unlimited readings",
      "Unlimited profiles",
      "All reading sections unlocked",
      "Daily & monthly horoscope",
      "Compatibility readings",
      "Detailed line overlay",
      "Natal chart",
      "PDF export",
    ],
  },
} as const;

export const ZODIAC_SIGNS = [
  "aries",
  "taurus",
  "gemini",
  "cancer",
  "leo",
  "virgo",
  "libra",
  "scorpio",
  "sagittarius",
  "capricorn",
  "aquarius",
  "pisces",
] as const;

export type ZodiacSign = (typeof ZODIAC_SIGNS)[number];
