import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export interface EmailTemplate {
  to: string;
  subject: string;
  html: string;
  text?: string;
}

export async function sendEmail(template: EmailTemplate): Promise<boolean> {
  try {
    await resend.emails.send({
      from: "Palmtell <noreply@palmtell.com>",
      to: template.to,
      subject: template.subject,
      html: template.html,
      text: template.text,
    });
    return true;
  } catch (error) {
    console.error("Email send error:", error);
    return false;
  }
}

export function createWelcomeEmail(userEmail: string, userName: string): EmailTemplate {
  return {
    to: userEmail,
    subject: "Welcome to Palmtell - Your Reading is Ready! 🌟",
    html: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Welcome to Palmtell</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc; }
            .container { max-width: 600px; margin: 0 auto; background: white; }
            .header { background: linear-gradient(135deg, #5B4FCF 0%, #F59B0B 100%); padding: 40px 20px; text-align: center; }
            .header h1 { color: white; margin: 0; font-size: 28px; font-weight: 700; }
            .content { padding: 40px 20px; }
            .button { display: inline-block; background: #5B4FCF; color: white; padding: 16px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; margin: 20px 0; }
            .footer { background: #f1f5f9; padding: 20px; text-align: center; color: #64748b; font-size: 14px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>✋ Welcome to Palmtell</h1>
            </div>
            <div class="content">
              <h2>Hi ${userName}!</h2>
              <p>Your palm reading is ready! We've analyzed your palm lines and created a personalized reading just for you.</p>
              
              <p>Your 7-day trial has started, giving you full access to:</p>
              <ul>
                <li>✨ Complete personality analysis</li>
                <li>🧭 Life path insights</li>
                <li>💼 Career guidance</li>
                <li>❤️ Relationship compatibility</li>
                <li>🏥 Health insights</li>
                <li>🍀 Lucky numbers and symbols</li>
              </ul>
              
              <div style="text-align: center;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard" class="button">View Your Reading</a>
              </div>
              
              <p><strong>Important:</strong> After 7 days, some sections will be locked unless you upgrade to Pro. No credit card required during your trial!</p>
            </div>
            <div class="footer">
              <p>Palmtell readings are generated by AI for entertainment purposes only.</p>
              <p>Not medical, psychological, financial, or legal advice.</p>
            </div>
          </div>
        </body>
      </html>
    `,
    text: `Welcome to Palmtell, ${userName}!

Your palm reading is ready! Your 7-day trial has started with full access to all features.

View your reading: ${process.env.NEXT_PUBLIC_APP_URL}/dashboard

After 7 days, some sections will be locked unless you upgrade to Pro.

Palmtell readings are for entertainment purposes only.`
  };
}

export function createTrialExpiryWarningEmail(userEmail: string, userName: string): EmailTemplate {
  return {
    to: userEmail,
    subject: "Your Palmtell trial expires tomorrow 📅",
    html: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Trial Expires Tomorrow</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc; }
            .container { max-width: 600px; margin: 0 auto; background: white; }
            .header { background: linear-gradient(135deg, #F59B0B 0%, #5B4FCF 100%); padding: 40px 20px; text-align: center; }
            .header h1 { color: white; margin: 0; font-size: 28px; font-weight: 700; }
            .content { padding: 40px 20px; }
            .button { display: inline-block; background: #F59B0B; color: white; padding: 16px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; margin: 20px 0; }
            .footer { background: #f1f5f9; padding: 20px; text-align: center; color: #64748b; font-size: 14px; }
            .highlight { background: #fef3c7; padding: 16px; border-radius: 8px; border-left: 4px solid #F59B0B; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>⏰ Trial Expires Tomorrow</h1>
            </div>
            <div class="content">
              <h2>Hi ${userName},</h2>
              
              <div class="highlight">
                <p><strong>Your 7-day trial expires tomorrow.</strong> After that, some features will be locked unless you upgrade to Pro.</p>
              </div>
              
              <p>What happens tomorrow:</p>
              <ul>
                <li>✅ Keep access: Personality, Life Path, Career</li>
                <li>🔒 Locked: Relationships, Health, Lucky Numbers</li>
                <li>🔒 Locked: Monthly horoscopes and compatibility readings</li>
              </ul>
              
              <p><strong>Upgrade to Pro ($9.99/month) to keep full access:</strong></p>
              <ul>
                <li>🔓 Unlock all reading sections</li>
                <li>📅 Monthly personalized horoscopes</li>
                <li>💕 Compatibility readings</li>
                <li>👥 Up to 3 profiles</li>
                <li>📊 10 readings per month</li>
              </ul>
              
              <div style="text-align: center;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL}/pricing" class="button">Upgrade to Pro</a>
              </div>
            </div>
            <div class="footer">
              <p>Questions? Reply to this email - we're here to help!</p>
            </div>
          </div>
        </body>
      </html>
    `,
    text: `Hi ${userName},

Your 7-day trial expires tomorrow. After that, some features will be locked.

What you'll keep: Personality, Life Path, Career
What gets locked: Relationships, Health, Lucky Numbers, Monthly horoscopes

Upgrade to Pro ($9.99/month) to keep full access: ${process.env.NEXT_PUBLIC_APP_URL}/pricing`
  };
}

export function createSubscriptionCanceledEmail(userEmail: string, userName: string, endDate: string): EmailTemplate {
  return {
    to: userEmail,
    subject: "Subscription Canceled - Access Continues Until " + endDate,
    html: `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Subscription Canceled</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; background-color: #f8fafc; }
            .container { max-width: 600px; margin: 0 auto; background: white; }
            .header { background: #64748b; padding: 40px 20px; text-align: center; }
            .header h1 { color: white; margin: 0; font-size: 28px; font-weight: 700; }
            .content { padding: 40px 20px; }
            .button { display: inline-block; background: #5B4FCF; color: white; padding: 16px 32px; text-decoration: none; border-radius: 8px; font-weight: 600; margin: 20px 0; }
            .footer { background: #f1f5f9; padding: 20px; text-align: center; color: #64748b; font-size: 14px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>Subscription Canceled</h1>
            </div>
            <div class="content">
              <h2>Hi ${userName},</h2>
              <p>We've processed your subscription cancellation. Your access will continue until <strong>${endDate}</strong>.</p>
              
              <p><strong>What happens next:</strong></p>
              <ul>
                <li>✅ Full access continues until ${endDate}</li>
                <li>📱 Your readings and profiles remain saved</li>
                <li>🔒 After ${endDate}, some features will be locked</li>
                <li>💳 No future charges</li>
              </ul>
              
              <p>Changed your mind? You can reactivate anytime before ${endDate}.</p>
              
              <div style="text-align: center;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL}/pricing" class="button">Reactivate Subscription</a>
              </div>
              
              <p>We're sorry to see you go! If you have feedback on how we can improve, please reply to this email.</p>
            </div>
            <div class="footer">
              <p>Thank you for being part of the Palmtell community!</p>
            </div>
          </div>
        </body>
      </html>
    `,
    text: `Hi ${userName},

Your subscription has been canceled. Access continues until ${endDate}.

After ${endDate}, some features will be locked but your readings remain saved.

Reactivate anytime: ${process.env.NEXT_PUBLIC_APP_URL}/pricing

Thank you for being part of Palmtell!`
  };
}
