import { Metadata } from "next";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Palmtell",
  description: "Terms of Service for Palmtell palm reading and astrology services. Read our terms and conditions for using our AI-powered palm analysis platform.",
  robots: "index, follow",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background py-16 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="font-serif text-4xl font-bold mb-4">Terms of Service</h1>
          <p className="text-muted-foreground">
            Last updated: January 1, 2024
          </p>
        </div>

        <div className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle>1. Acceptance of Terms</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                By accessing and using Palmtell ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
              <p>
                These Terms of Service ("Terms") govern your use of our website located at palmtell.com (the "Service") operated by Palmtell ("us", "we", or "our").
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. Description of Service</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                Palmtell provides AI-powered palm reading and astrology services for entertainment purposes only. Our service includes:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Palm photo analysis using artificial intelligence</li>
                <li>Personality insights based on palm reading traditions</li>
                <li>Daily and monthly horoscope content</li>
                <li>Compatibility readings between profiles</li>
                <li>Educational content about palmistry and astrology</li>
              </ul>
              <div className="p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
                <p className="font-semibold text-yellow-800 dark:text-yellow-200">
                  Important Disclaimer: All readings and content provided by Palmtell are generated by AI for entertainment purposes only. They are not medical, psychological, financial, or legal advice.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>3. User Accounts and Registration</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                To access certain features of the Service, you may be required to create an account. You agree to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Provide accurate, current, and complete information during registration</li>
                <li>Maintain and promptly update your account information</li>
                <li>Maintain the security of your password and account</li>
                <li>Accept responsibility for all activities under your account</li>
                <li>Notify us immediately of any unauthorized use of your account</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>4. Subscription Plans and Billing</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <h4 className="font-semibold">Trial Period</h4>
              <p>
                New users receive a 7-day trial with full access to all features. No credit card is required to start the trial. After the trial period, some features will be locked unless you upgrade to a paid plan.
              </p>
              
              <h4 className="font-semibold">Paid Subscriptions</h4>
              <p>
                Paid subscriptions are billed monthly or annually in advance. All fees are non-refundable except as required by law. We reserve the right to change our pricing with 30 days notice.
              </p>
              
              <h4 className="font-semibold">Cancellation</h4>
              <p>
                You may cancel your subscription at any time. Your access will continue until the end of your current billing period. No refunds will be provided for partial periods.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>5. Privacy and Data Protection</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference.
              </p>
              <p>
                By using our Service, you consent to the collection and use of your information as outlined in our Privacy Policy.
              </p>
              <Link href="/privacy" className="text-primary hover:underline">
                Read our Privacy Policy →
              </Link>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>6. User Content and Conduct</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                You are responsible for any content you upload, including palm photos. You agree not to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Upload content that is illegal, harmful, or violates others' rights</li>
                <li>Use the Service for any unlawful purpose</li>
                <li>Attempt to gain unauthorized access to our systems</li>
                <li>Interfere with or disrupt the Service</li>
                <li>Use automated systems to access the Service without permission</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>7. Intellectual Property</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                The Service and its original content, features, and functionality are owned by Palmtell and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
              </p>
              <p>
                You retain ownership of content you upload, but grant us a license to use, store, and process it to provide the Service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>8. Disclaimers and Limitations</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg">
                <p className="font-semibold text-red-800 dark:text-red-200 mb-2">
                  IMPORTANT DISCLAIMERS:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-red-700 dark:text-red-300">
                  <li>All readings are for entertainment purposes only</li>
                  <li>Results are not medical, psychological, financial, or legal advice</li>
                  <li>We make no guarantees about accuracy or outcomes</li>
                  <li>The Service is provided "as is" without warranties</li>
                  <li>We are not liable for decisions made based on readings</li>
                </ul>
              </div>
              <p>
                To the maximum extent permitted by law, we disclaim all warranties and limit our liability for any damages arising from your use of the Service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>9. Termination</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                We may terminate or suspend your account and access to the Service immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
              </p>
              <p>
                Upon termination, your right to use the Service will cease immediately. All provisions that should survive termination will survive, including ownership provisions and liability limitations.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>10. Changes to Terms</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                We reserve the right to modify these Terms at any time. We will notify users of any material changes by posting the new Terms on this page and updating the "Last updated" date.
              </p>
              <p>
                Your continued use of the Service after any changes constitutes acceptance of the new Terms.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>11. Governing Law</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
              </p>
              <p>
                Any disputes arising from these Terms or your use of the Service shall be resolved in the courts of [Your Jurisdiction].
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>12. Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                If you have any questions about these Terms of Service, please contact us:
              </p>
              <ul className="space-y-2">
                <li>Email: legal@palmtell.com</li>
                <li>Website: <Link href="/" className="text-primary hover:underline">palmtell.com</Link></li>
              </ul>
            </CardContent>
          </Card>
        </div>

        <div className="mt-12 text-center">
          <p className="text-sm text-muted-foreground">
            By using Palmtell, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </p>
        </div>
      </div>
    </div>
  );
}
